### ISSUE TITLE
Create Login & Signup Layout in XML

### ISSUE THREAD

**Issue by Rohit-554** [dsc-iem/Dristi-Hacktoberfest22#3]
Hey,
This app needs a Login and Signup Layouts 
<br>
**Like this**
<img src="https://user-images.githubusercontent.com/48874687/196020882-e452d395-6f20-434f-8df1-bcbb29d9d813.png" width="200" height="400" /> <img src="https://user-images.githubusercontent.com/48874687/196021106-8b5eced7-6611-4dd2-971b-5cedf92004d9.png" width="200" height="400"/>

- Create the xml layout (You may change the design the above is only for reference)
- The layout should be inside the Layout folder (named as Signin and Signup)
 
  ![layout](https://user-images.githubusercontent.com/48874687/196021255-386bc646-b5d8-4789-9274-d71744b4ba91.png) 
- After adding the layout create a pull request and don't forgot to add the hactoberfest or hactoberfest2022 in your pr tags

  **Happy Hacking**
    >You can take help from Yt

**Comment by RohitLakra299** [comment]
Hi @Rohit-554, can you assign me this task.

**Comment by Rohit-554** [comment]
>You can Start Working
Follow the guidelines as mentioned in the issue
